export enum ProductStatus {
    PAUSE = "PAUSE",
    PROCESS = "PROCESS",
    RECOMEND = "RECOMEND",
    DELETE = "DELETE",
}

export enum ProductType {
    MAKEUP = "MAKEUP",
    SKINCARE = "SKINCARE",
    HAIR = "HAIR",
    FRAGRANCE="FRAGRANCE",
    TOOLS_BRUSHES = "TOOLS_BRUSHES",
    BATH_BODY = "BATH_BODY",
    BEAUTYUNDER20$= "BEAUTYUNDER20$",
    ACCESSORIES ="ACCESSORIES",
}


export enum  ProductCollection{
    EYE = "EYE",
    LIP = "LIP",
    CHEEK = "CHEEK",

    MASK = "MASK",
    CLEANSER = "CLEANSER",
    SUNSCREEN = "SUNSCREEN",
    MOISTURIZER = "MOISTURIZER",

    TREATMENTS = "TREATMENTS",
    STYLING = "STYLING",
    SHAMPOO_CONDITIONER= "SHAMPOO_CONDITIONER",

    CANDLES = "CANDLES",
    PERFUME = "PERFUME",
    COLLOGNE= "COLLOGNE",

    HAIRTOOLS = "HAIRTOOLS",
    BEAUTYTOOLS = "BEAUTYTOOLS",
    BRUSHES_APPLICCATORS= "BRUSHES_APPLICCATORS",

    BATH_SHOWER = "BATH_SHOWER",

    ALL_CHEAP="ALL_CHEAP",

    ALL_ACCESSORIES="ALL_ACCESSORIES",

    ALLTYPE= "ALLTYPE"
}

export enum Gender{
    MEN="MEN",
    WOMEN="WOMEN",
}
export enum ProductBrand {
    CHANEL = "CHANEL",
    DIOR = "DIOR",
    PRADA = "PRADA",
    BURBERRY ="BURBERRY"
}


